import java.util.ArrayList;

public class AnalisisEstatico{
    
    ArrayList<AST> reglas;
    
    public void redundancia(ArrayList<AST> reglas){
        this.reglas=reglas;
        
        for(int i=0; i<reglas.size(); i++){ 
            AST r1 = reglas.get(i);
            String condition1= r1.condicion;
            String action1= r1.accion;
            for(int j=i+1; j<reglas.size(); j++){
                AST r2 = reglas.get(j);
                String condition2= r2.condicion;
                String action2= r2.accion;
                if(condition1.equals(condition2) && action1.equals(action2)){
                    
                    System.out.println("Redundant rules: "+ r1.nombreRegla+", "+r2.nombreRegla);
                }
            }
        }
    }
    
    public void conflictos(ArrayList<AST> reglas){
        this.reglas=reglas;
       
        for(int i=0; i<reglas.size(); i++){
            AST r1 =reglas.get(i);
            String action1=r1.accion;
            for(int j=i+1; j<reglas.size(); j++){
                AST r2= reglas.get(j);
                String action2=r2.accion;
                if(action1.equals(action2)){
                    System.out.println("Action "+ r1.accion+" generated by "+r1.nombreRegla+", "+r2.nombreRegla);
                }                
            }
        }
    }
    
    public void inactivo(ArrayList<AST> reglas){
        boolean activo=false;
        for(int i=0; i<reglas.size(); i++){
            AST r1=reglas.get(i);
            activo= r1.ejecutado;
            if(activo==false){
                System.out.println("Potentially inactive rule: "+ r1.nombreRegla);
            }
        }
        
    }
}
